version: "3.7"
services:
  app:
    container_name: mfe-deps-server
    restart: always
    build: .
    image: "filoxo/mfe-deps-server:latest"
    environment:
      - MONGODB_URL=mongodb://mongodb/mfedepsserver
    command: npm run dev
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:latest"
    container_name: mfe-deps-server-mongodb
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      MONGODB_USER: mfe-deps-user
      MONGODB_PASSWORD: mfe-deps-password
