version: "3.7"
services:
  app:
    container_name: mfe-deps-server
    restart: always
    build: .
    image: "filoxo/mfe-deps-server:latest"
    command: npm run dev
    ports:
      - 3000:3000
    expose:
      - 3000
