version: '3.7'

x-app-credentials: &app-credentials
  APP_DB_USER: mfe-deps-user
  APP_DB_PW: mfe-deps-password
  MONGO_INITDB_DATABASE: dependencies

services:
  app:
    container_name: mfe-deps-server
    restart: always
    build: .
    init: true
    image: 'filoxo/mfe-deps-server:latest'
    environment: *app-credentials
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - mongodb
  mongodb:
    image: 'mongo:latest'
    container_name: mfe-deps-server-mongodb
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      <<: *app-credentials
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
